from __future__ import annotations

import json
import math
from pathlib import Path

import numpy as np

from .config import RoiConfig
from .models import LoadedPointCloud, PlanePatch


def _ensure_parent(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)


def _roi_mask(points: np.ndarray, roi: RoiConfig | None) -> np.ndarray:
    if roi is None or not roi.enabled or roi.minimum is None or roi.maximum is None:
        return np.ones(len(points), dtype=bool)
    minimum = np.asarray(roi.minimum, dtype=float)
    maximum = np.asarray(roi.maximum, dtype=float)
    return np.all(points >= minimum, axis=1) & np.all(points <= maximum, axis=1)


def load_las_points(
    las_path: Path, roi: RoiConfig | None = None, chunk_size: int = 1_000_000
) -> LoadedPointCloud:
    try:
        import laspy
    except ImportError as exc:
        raise RuntimeError("laspy is required to read LAS files. Run `pip install -e .`.") from exc

    selected_chunks: list[np.ndarray] = []
    source_total = 0
    selected_total = 0

    with laspy.open(str(las_path)) as reader:
        for chunk in reader.chunk_iterator(chunk_size):
            points = np.column_stack((chunk.x, chunk.y, chunk.z)).astype(np.float64, copy=False)
            source_total += len(points)
            mask = _roi_mask(points, roi)
            if not np.any(mask):
                continue
            kept = points[mask]
            selected_total += len(kept)
            selected_chunks.append(kept)

    if selected_chunks:
        merged = np.concatenate(selected_chunks, axis=0)
    else:
        merged = np.empty((0, 3), dtype=np.float64)

    return LoadedPointCloud(
        points=merged,
        source_total_points=source_total,
        selected_points=selected_total,
    )


def load_las_preview_points(
    las_path: Path,
    chunk_size: int = 1_000_000,
    max_points: int = 400_000,
) -> np.ndarray:
    try:
        import laspy
    except ImportError as exc:
        raise RuntimeError("laspy is required to read LAS files. Run `pip install -e .`.") from exc

    preview_chunks: list[np.ndarray] = []

    with laspy.open(str(las_path)) as reader:
        total_points = int(reader.header.point_count)
        stride = max(1, int(math.ceil(total_points / max(1, max_points))))
        for chunk in reader.chunk_iterator(chunk_size):
            points = np.column_stack((chunk.x, chunk.y, chunk.z)).astype(np.float64, copy=False)
            preview_chunks.append(points[::stride])

    if not preview_chunks:
        return np.empty((0, 3), dtype=np.float64)
    return np.concatenate(preview_chunks, axis=0)


def write_obj(output_path: Path, patches: list[PlanePatch]) -> None:
    _ensure_parent(output_path)
    lines: list[str] = ["# Generated by las-to-obj"]
    vertex_offset = 1

    for patch in patches:
        lines.append(f"o {patch.name}")
        lines.append(f"g {patch.label}")
        for vertex in patch.vertices:
            lines.append(f"v {vertex[0]:.6f} {vertex[1]:.6f} {vertex[2]:.6f}")
        for face in patch.faces:
            a, b, c = face
            lines.append(f"f {a + vertex_offset} {b + vertex_offset} {c + vertex_offset}")
        vertex_offset += len(patch.vertices)

    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_report(output_path: Path, report: dict[str, object]) -> None:
    _ensure_parent(output_path)
    output_path.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
